version: '3'
services:
  app:
    build: ./app
    ports:
      - 7890:8000
    volumes:
     - './app:/app'
    environment:
      REDIS_URL: redis://redis:6379
      HLS_URL: hls:1935
    depends_on:
      - redis
      # - mongo
    restart: unless-stopped

  
  yolo_main:
    build: ./app
    command: ['ml.py', 'yolo5', 'main']
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
  yolo_webcam:
    build: ./app
    command: ['ml.py', 'yolo5', 'webcam:pv', '--is-jpg']
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379
    expose:
     - '6379'
    volumes:
      - ./redis/redis_6789.conf:/usr/local/etc/redis/redis.conf
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  # a dashboard to view redis
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - '8035:8001'
    # volumes:
    #   - ./redisinsight:/db 

  # redisinsight_init:
  #   image: curlimages/curl
  #   restart: on-failure
  #   depends_on:
  #     - redis
  #     - redisinsight
  #   command: >
  #     localhost:8035/add/?name=redis&host=redis&port=6379

  hls:
    build: ./hls
    restart: unless-stopped
    ports:
      - 1936:1935

  

  # background task management

  # # celery broker
  # celery_rabbitmq:
  #   image: rabbitmq:3.6.6
  #   ports:
  #     - "5672:5672"
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=mypass

  # # celery result backend
  # celery_redis:
  #   image: redis
  #   ports:
  #    - "6381:6379"

  # # celery worker - duplicate for multiple processes? use replicas=x?
  # celery_worker:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   image: madefire/chordtest
  #   command: ['celery', '-A', 'app.workers.app', 'worker', '-l', 'info']
  #   environment:
  #     - BROKER_URL=amqp://admin:mypass@celery_rabbitmq:5672//
  #     - RESULT_BACKEND=redis://celery_redis:6381/0
  #     - C_FORCE_ROOT=true
  #   volumes:
  #     - ./:/app/
  #   depends_on:
  #     - celery_rabbitmq
  #     - celery_redis


  # storing recipes

  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: something
  #     MONGO_INITDB_ROOT_PASSWORD: coffee
  #     MONGO_INITDB_DATABASE: recipes

  # mongo-express:
  #   image: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: something
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: coffee
  #     ME_CONFIG_MONGODB_URL: mongodb://something:coffee@mongo:27017/
