{
 "title": "NGINX HLS",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Uptime (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_rtmp_server_uptime_seconds_total{}"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nginx_rtmp_server_current_streams{}"
    }
   ]
  },
  {
   "title": "Incoming / Outgoing Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "nginx_rtmp_server_incoming_bytes_total{}"
    },
    {
     "expr": "nginx_rtmp_server_outgoing_bytes_total{}"
    }
   ]
  },
  {
   "title": "Recv / Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "nginx_rtmp_server_receive_bytes{}"
    },
    {
     "expr": "nginx_rtmp_server_transmit_bytes{}"
    }
   ]
  }
 ]
}